### ISSUE TITLE
Recording while screen capture select open produces empty folders

### ISSUE THREAD

**Issue by stevenrick** [WeibelLab/ChronoSense#66]
Reproduction
- Open ChronoSense
- Select/Open ScreenCapture device
- Click Start Recording before selecting a screen capture source
- Recording won't start but output folders will be produced <-- bug

**Comment by riduong** [comment]
Adressed in #65

**Comment by riduong** [comment]
Current functionality doesn't allow any video or audio stream to be recorded if screen capture is up and no screen is selected
